using Hangfire;
using JobRadar.Application.Messages;
using JobRadar.Domain.Entities;
using JobRadar.Domain.Enums;
using JobRadar.Infrastructure.Persistence;
using MassTransit;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace JobRadar.Workers.Ingestion;

public class FetchSourceJob
{
    private readonly AppDbContext _dbContext;
    private readonly Services.RssFeedFetcher _rssFetcher;
    private readonly Services.TelegramFetcher _telegramFetcher;
    private readonly IPublishEndpoint _publishEndpoint;
    private readonly ILogger<FetchSourceJob> _logger;

    public FetchSourceJob(
        AppDbContext dbContext,
        Services.RssFeedFetcher rssFetcher,
        Services.TelegramFetcher telegramFetcher,
        IPublishEndpoint publishEndpoint,
        ILogger<FetchSourceJob> logger)
    {
        _dbContext = dbContext;
        _rssFetcher = rssFetcher;
        _telegramFetcher = telegramFetcher;
        _publishEndpoint = publishEndpoint;
        _logger = logger;
    }

    [AutomaticRetry(Attempts = 0)] // Polly handles external retries; don't retry business logic excessively if it's fundamentally broken
    public async Task ExecuteAsync(Guid sourceId)
    {
        _logger.LogInformation("Starting FetchSourceJob for SourceId: {SourceId}", sourceId);

        var source = await _dbContext.Sources.FirstOrDefaultAsync(s => s.Id == sourceId);
        if (source == null || source.Status != SourceStatus.Active)
        {
            _logger.LogWarning("Source {SourceId} not found or not active. Skipping.", sourceId);
            return;
        }

        try
        {
            switch (source.Type)
            {
                case SourceType.RssFeed:
                    await ProcessRssFeedAsync(source);
                    break;
                case SourceType.TelegramChannel:
                    await ProcessTelegramChannelAsync(source);
                    break;
                default:
                    _logger.LogWarning("Source {SourceId} has unsupported type {Type}. Skipping.", sourceId, source.Type);
                    break;
            }

            source.RecordFetch();
            await _dbContext.SaveChangesAsync();
            _logger.LogInformation("Successfully completed FetchSourceJob for SourceId: {SourceId}", sourceId);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error processing SourceId: {SourceId}", sourceId);
            throw; // Let Hangfire know it failed
        }
    }

    private async Task ProcessRssFeedAsync(Source source)
    {
        var items = await _rssFetcher.FetchAsync(source.Url);
        foreach (var item in items)
        {
            var rawUrl = item.Link;
            // Check if post already exists
            var exists = await _dbContext.RawPosts.AnyAsync(p => p.SourceId == source.Id && p.RawUrl == rawUrl);
            if (!exists)
            {
                var rawPost = RawPost.Create(source.Id, item.Content, rawUrl);
                _dbContext.RawPosts.Add(rawPost);
                
                await _dbContext.SaveChangesAsync(); // Save to generate ID (already generated by GUID, but good to persist before event)
                
                await _publishEndpoint.Publish(new RawPostCreatedEvent(
                    RawPostId: rawPost.Id,
                    SourceId: source.Id,
                    RawUrl: rawPost.RawUrl,
                    FetchedAt: rawPost.FetchedAt
                ));
            }
        }
    }

    private async Task ProcessTelegramChannelAsync(Source source)
    {
        // Extract channel username from URL, e.g. "https://t.me/channelname" -> "channelname"
        var username = source.Url.Split('/').Last().Trim();
        var messages = await _telegramFetcher.FetchRecentMessagesAsync(username);

        foreach (var msg in messages)
        {
            var rawUrl = $"https://t.me/{username}/{msg.MessageId}";
            var exists = await _dbContext.RawPosts.AnyAsync(p => p.SourceId == source.Id && p.RawUrl == rawUrl);
            
            if (!exists)
            {
                var rawPost = RawPost.Create(source.Id, msg.Content, rawUrl);
                _dbContext.RawPosts.Add(rawPost);
                
                await _dbContext.SaveChangesAsync();
                
                await _publishEndpoint.Publish(new RawPostCreatedEvent(
                    RawPostId: rawPost.Id,
                    SourceId: source.Id,
                    RawUrl: rawPost.RawUrl,
                    FetchedAt: rawPost.FetchedAt
                ));
            }
        }
    }
}
